#!/bin/sh

if [ $# = 0 ]; then
  echo 
  echo "Use the one of following commands:"
  echo
  echo "1) Switch to nvidia prime"
  echo "2) Switch to intel graphics"
  echo

 read command

  if [ "$command" = "1" ]; then
  sudo -E nohup "$0" nvidia
  fi

  if [ "$command" = "2" ]; then
  sudo -E nohup "$0" intel
  fi

  exit
fi


if [ `whoami` != "root" ]; then
  echo "You must run it as root";
  exit
fi


if [ "$1" = "nvidia" ] && [ `prime-select query` != "nvidia" ]
then
  service lightdm stop
  prime-select nvidia
  cp /home/janseng/projects/optirun-prime-switcher/xorg.conf.nvidia /etc/X11/xorg.conf
  service lightdm restart
elif [ "$1" = "nvidia" ]; then
  echo "You can not switch to nvidia: it is already active.";
  glxinfo | grep OpenGL
fi


if [ "$1" = "intel" ] && [ `prime-select query` != "intel" ]
then
  service lightdm stop
  prime-select intel
  service lightdm restart
elif [ "$1" = "intel" ]; then
  echo "You can not switch to intel: it is already active.";
  glxinfo | grep OpenGL
fi
